test

diff --git a/.github/workflows/iam-validate.yml b/.github/workflows/iam-validate.yml
--- a/.github/workflows/iam-validate.yml
+++ b/.github/workflows/iam-validate.yml
@@ -24,36 +24,39 @@ jobs:
   do_not_merge:
     runs-on: 'ubuntu-latest'
     steps:
+      - name: 'Checkout Triggering Branch'
+        uses: 'actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab' # ratchet:actions/checkout@v3
+        with:
+          ref: '${{ github.event.pull_request.head.ref }}'
+      # - id: 'fail'
+      #   if: '${{ hashFiles(''iam.yaml'') != '''' }}'
+      #   run: 'exit 1'
       - id: 'fail'
         run: |
           if [ -f "iam.yaml" ]; then
-            echo exit 1
+            exit 1
           fi
-
-  validate:
+  check_files:
     runs-on: 'ubuntu-latest'
-    name: 'Validate Request'
+    name: 'Check file existence'
+    outputs:
+      has_files: '${{ steps.result.HAS_FILES }}'
     steps:
       - name: 'Checkout Triggering Branch'
         uses: 'actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab' # ratchet:actions/checkout@v3
         with:
           ref: '${{ github.event.pull_request.head.ref }}'
-      - name: 'Setup Go'
-        uses: 'actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568' # ratchet:actions/setup-go@v3
-        # with:
-        #   go-version: '${{ inputs.go_version }}'
-      # - name: 'Install AOD CLI'
-      #   run: 'go install github.com/abcxyz/access-on-demand/cmd/aod@latest'
-        # with:
-        #   go-version: '${{ inputs.go_version }}'
-      # Request will not be validated when iam.yaml file does not exist in the
-      # case of a pull_request_review event, instead it prints out a notice.
-      - name: 'Validate IAM Request'
-        env:
-          FILE_PATH: '${{ github.workspace }}/iam.yaml'
+      - id: 'result'
+        if: '${{ hashFiles(''iam.yaml'') != '''' }}'
         run: |
-          if [ -f "iam.yaml" ]; then
-            aod iam validate -path $FILE_PATH
-          else
-            echo "::notice title=IAM Request Validation::Skip because iam.yaml is not found"
-          fi
+          echo "HAS_FILES=true" >> "$GITHUB_OUTPUT"
+
+  validate:
+    needs: 'check_files'
+    if: '${{ needs.check_files.outputs.has_files == ''true''}}'
+    uses: 'abcxyz/access-on-demand/.github/workflows/validate.yml@main' # Currently using main, change here to ping the tag.
+    # To specify inputs, change the repository variables.
+    # Details: https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
+    with:
+      aod_cli_version: '${{ vars.aod_cli_version || ''latest'' }}'
+      go_version: '${{ vars.go_version || ''1.20'' }}'
